---
title: Render een sneeuwscène
hero_image: images/banner.png
description: Render een sneeuwscène-animatie met Blender
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: art, weather
technologies: blender
site_areas: projects
hardware: ''
software: blender
version: 3
last_tested: 2017-01-01
steps:
  - title: Inleiding
  - title: Controleer je animatie
  - title: Render-instellingen
  - title: Renderen
  - title: "Uitdaging: andere instellingen"
