title: Render a snow scene
hero_image: images/banner.png
description: Render a snow scene animation using Blender
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 # possible values: 1, 2 or 3
listed: true
ingredient: false
copyedit: true
curriculum: creator, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: "art&design, nature/outside/weather"
technologies: "blender"
site_areas:
steps:
  - title: Introduction
  - title: What you will need
  - title: Check your animation
  - title: Render settings
  - title: Render
  - title: "Challenge: different settings"
