---
title: बर्फ का दृश्य प्रस्तुत करें
hero_image: images/banner.png
description: Blender का उपयोग करके बर्फ के दृश्य का एनिमेशन प्रस्तुत करें।
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: art, weather
technologies: blender
site_areas: projects
hardware: ''
software: blender
version: 3
last_tested: 2017-01-01
steps:
- title: भूमिका
  completion: engaged
- title: अपने एनिमेशन की जाँच करें
- title: सेटिंग्स प्रस्तुत करें
- title: प्रस्तुत करें
  completion: internal
- title: 'चुनौती: विभिन्न सेटिंग्स'
