---
title: Render a snow scene
hero_image: images/banner.png
description: Render a snow scene animation using Blender
theme: vermell #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, disseny-1, programació-0, phys-comp-0, fabricació-0, comunitat-0
interests: art, weather
technologies: blender
site_areas: projectes
hardware: ''
software: blender
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introducció
  - 
    title: Què necessitaràs
  - 
    title: Check your animation
  - 
    title: Render settings
  - 
    title: Render
  - 
    title: "Challenge: different settings"
