---
title: Render a snow scene
hero_image: images / banner.png
description: Render a snow scene animation using Blender
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
interests: art, weather
technologies: blender
site_areas: projekty
hardware: ''
software: blender
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Wprowadzenie
  - 
    title: Co będzie potrzebne
  - 
    title: Check your animation
  - 
    title: Render settings
  - 
    title: Render
  - 
    title: "Challenge: different settings"
